JOB = [ name: "MongoDB.ServerStatus.MemoryInfo" ]	

FETCHACTION={
	def finalData = [:]
	// Get information of server
	def dbMongo = mongo.getDB("admin")
	def serverStatusStr = dbMongo.command("serverStatus").toString()
	def mapDataServerStatus = slurper.parseText(serverStatusStr)
	finalData['MemoryInfo'] = mapDataServerStatus['mem']
	finalData['MetricsInfo'] = mapDataServerStatus['metrics']
	return finalData
}

DEST = parameters.dest
