JOB = [ name: "MongoDB.ServerStatus.NetworkStats" ]	
FETCHACTION={
	def finalData = [:]
	def dbMongo = mongo.getDB("admin");
	def mapDataServerStatus = dbMongo.command("serverStatus")
	finalData['connections'] = mapDataServerStatus['connections']
	finalData['network'] = mapDataServerStatus['network']
	finalData['cursors'] = mapDataServerStatus['cursors']
	finalData['dur'] = mapDataServerStatus['dur']
	return finalData
}
DEST = parameters.dest