JOB = [ name: "MongoDB.HostInfo.Extra" ]	
FETCHACTION = {
	def finalData = [:]
	def dbMongo = mongo.getDB("admin");
	def hostInfoStr = dbMongo.command("hostInfo").toString()
	def mapDataHostInfo = slurper.parseText(hostInfoStr)
	finalData['numPagesNum'] = mapDataHostInfo['extra']['numPages']
	finalData['pageSizeKb'] = mapDataHostInfo['extra']['pageSize'] / 1024
	return finalData
}
DEST = parameters.dest
