JOB = [ name: "MongoDB.HostInfo.Os" ]	
FETCHACTION = {
	def finalData = [:]
	def dbMongo = mongo.getDB("admin");
	def hostInfoStr = dbMongo.command("hostInfo").toString()
	def mapDataHostInfo = slurper.parseText(hostInfoStr)
	finalData['nameNm'] = mapDataHostInfo['os']['name']
	finalData['typeStr'] = mapDataHostInfo['os']['type']
	finalData['versionStr'] = mapDataHostInfo['os']['version']
	return finalData
}
DEST = parameters.dest
